In [7]:
import numpy as np

def lanczos_iteration(A, m, v_init):
    n = A.shape[0]
    V = np.zeros((n, m))
    T = np.zeros((m, m))
    v = v_init / np.linalg.norm(v_init)
    V[:, 0] = v
    beta = 0

    for j in range(m):
        w = A @ v
        if j > 0:
            w -= beta * V[:, j - 1]
        alpha = np.dot(w, v)
        T[j, j] = alpha
        w -= alpha * v
        beta = np.linalg.norm(w)
        if beta < 1e-10 or j == m - 1:
            break
        T[j, j + 1] = beta
        T[j + 1, j] = beta
        v = w / beta
        V[:, j + 1] = v

    return V, T

def implicit_restarted_lanczos(A, num_eigenvalues, max_iter=100, m=50):
    n = A.shape[0]
    v_init = np.random.rand(n)
    converged = False
    eigenvalues = None
    eigenvectors = None

    for i in range(max_iter):
        V, T = lanczos_iteration(A, m, v_init)
        evals, evecs = np.linalg.eigh(T)
        idx = np.argsort(evals)[-num_eigenvalues:]
        evals = evals[idx]
        evecs = evecs[:, idx]
        
        eigenvalues = evals
        eigenvectors = V @ evecs
        
        # Check convergence
        residuals = np.linalg.norm(A @ eigenvectors - eigenvectors * eigenvalues, axis=0)
        if np.all(residuals < 1e-6):
            converged = True
            break
        
        # Restart vector
        v_init = eigenvectors[:, -1]

    if not converged:
        print("Warning: IRLM did not converge within the maximum number of iterations.")
    
    return eigenvalues, eigenvectors

# 示例使用：
n = 100
A = np.random.rand(n, n)
A = (A + A.T) / 2  # 保证矩阵对称
num_eigenvalues = 5
eigenvalues, eigenvectors = implicit_restarted_lanczos(A, num_eigenvalues)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [ 0.         0.         0.         0.        49.9082113]
Eigenvectors:
 [[ 0.          0.          0.          0.         -0.09887957]
 [ 0.          0.          0.          0.         -0.10156765]
 [ 0.          0.          0.          0.         -0.09991936]
 [ 0.          0.          0.          0.         -0.10005266]
 [ 0.          0.          0.          0.         -0.10096536]
 [ 0.          0.          0.          0.         -0.1016533 ]
 [ 0.          0.          0.          0.         -0.09878968]
 [ 0.          0.          0.          0.         -0.10049895]
 [ 0.          0.          0.          0.         -0.09866112]
 [ 0.          0.          0.          0.         -0.09987663]
 [ 0.          0.          0.          0.         -0.09859703]
 [ 0.          0.          0.          0.         -0.09729221]
 [ 0.          0.          0.          0.         -0.09956845]
 [ 0.          0.          0.          0.         -0.10632924]
 [ 0.          0.          0.    

In [8]:
np.linalg.eigh(A)

EighResult(eigenvalues=array([-3.93389608e+00, -3.79899296e+00, -3.60097258e+00, -3.47448704e+00,
       -3.34090704e+00, -3.14846305e+00, -3.05057507e+00, -2.95509077e+00,
       -2.90212373e+00, -2.79577964e+00, -2.69904748e+00, -2.66185658e+00,
       -2.56015146e+00, -2.42069816e+00, -2.29350893e+00, -2.27351426e+00,
       -2.12746532e+00, -2.10233918e+00, -1.95747322e+00, -1.90950680e+00,
       -1.84734280e+00, -1.78712687e+00, -1.70258698e+00, -1.66275814e+00,
       -1.58762941e+00, -1.52113356e+00, -1.45381164e+00, -1.36606212e+00,
       -1.35998819e+00, -1.24815095e+00, -1.21574598e+00, -1.12730189e+00,
       -1.03356177e+00, -9.95105209e-01, -8.70543930e-01, -8.21812370e-01,
       -7.49514528e-01, -7.34669864e-01, -6.56349956e-01, -5.55513621e-01,
       -5.45460426e-01, -4.98611904e-01, -4.60952871e-01, -4.19684631e-01,
       -3.10914076e-01, -2.32652358e-01, -6.06429354e-02, -3.50466105e-02,
        1.73678064e-03,  3.94499495e-02,  9.33910907e-02,  1.88104886e-01,
  